baseURL = "/"
title = "Decred — links and resources"
languageCode = "en-us"

[params]
    suggestionsLink = "https://github.com/planetdecred/decredpower/issues"
    lastUpdated = "Last updated 2020-07-13"
